### ISSUE TITLE
Headers inside request body

### ISSUE THREAD

**Issue by jim256** [DragonOfShuu/KSLHax#2]
Love this project!

I noticed in [line 52 of hax.py](https://github.com/DragonOfShuu/KSLHax/blob/5497f0fc0e4d28f1a22a96664f9a79017d46cd3b/hax.py#L52) that you have a headers key inside of your request body, and that you also separately pass in (different) headers later on in [line 65 of haxy.py](https://github.com/DragonOfShuu/KSLHax/blob/5497f0fc0e4d28f1a22a96664f9a79017d46cd3b/hax.py#L65) when you actually hit the API.

Why is that? Are both needed?

**Comment by DragonOfShuu** [comment]
Hey sorry I didn't get to this until now, GitHub did not notify me of your issue.

Anyways, yes both headers are necessary. This is because when you make the request, it actually goes to a proxy server first, then the backend server. So, the headers on line 52 are the headers used to make the request to the backend, and the headers on line 65 are for the request to the proxy server.

If that's hard to understand, let me give you a step by step instead:
 - My Python requests cars from the server, and passes the data to the proxy
 - The proxy utilizes the headers included in the data to make the request to the backend (thus why there's not only headers, but also the method AND the body)
 - The backend returns the cars to the proxy
 - The proxy returns the data to my Python
